@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzYxNjM2MzF9.Ppa6iXnNZKCmpd9Rm3LnvftFDdTwGSSSze4_POwJVU4
@hostname = http://localhost:3000

### EXPENSES INDEX
GET {{hostname}}/expenses
Authorization: Bearer {{jwt}}

### EXPENSES CREATE
POST {{hostname}}/expenses
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "date": "2021-10-22",
  "amount": 30.06,
  "category": "Gas & Car",
  "description": "King Soopers gas on way to Staunton",
  "user_id": 1
}

### EXPENSES SHOW
GET {{hostname}}/expenses/ID-HERE
Authorization: Bearer {{jwt}}

### EXPENSES UPDATE
PATCH {{hostname}}/expenses/ID-HERE
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "date": "2021-11-04"
}

### EXPENSES DESTROY
DELETE {{hostname}}/expenses/ID-HERE
Authorization: Bearer {{jwt}}

### EXPENSES MONTHLY TOTALS
GET {{hostname}}/monthly_totals
Authorization: Bearer {{jwt}}

### CATEGORY TOTALS
GET {{hostname}}/category_totals
Authorization: Bearer {{jwt}}

### ------------------------------------------------------------------ ###

### INCOMES INDEX
GET {{hostname}}/incomes
Authorization: Bearer {{jwt}}

### INCOMES CREATE
POST {{hostname}}/incomes
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "date": "2020-10-26",
  "amount": 2400.00,
  "category": "Financial Support",
  "description": "Financial support from Dad",
  "user_id": 1
}

### INCOMES SHOW
GET {{hostname}}/incomes/ID-HERE
Authorization: Bearer {{jwt}}

### INCOMES UPDATE
PATCH {{hostname}}/incomes/ID-HERE
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "date": "2021-11-04"
}

### INCOMES DESTROY
DELETE {{hostname}}/incomes/ID-HERE
Authorization: Bearer {{jwt}}

### ------------------------------------------------------------------ ###

### MONTHLY BALANCES INDEX
GET {{hostname}}/monthly_balances
Authorization: Bearer {{jwt}}

### MONTHLY BALANCES CREATE
POST {{hostname}}/monthly_balances
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "month": 11,
  "year": 2021,
  "checking1": 0,
  "checking2": 0,
  "savings1": 0,
  "savings2": 0,
  "credit_card1": 0,
  "credit_card2": 0,
  "credit_card3": 0,
  "credit_card4": 0,
  "loan1": 0,
  "loan2": 0,
  "personal_IRA": 0,
  "user_id": 1
}

### MONTHLY BALANCES SHOW
GET {{hostname}}/monthly_balances/2
Authorization: Bearer {{jwt}}

### MONTHLY_BALANCES UPDATE
PATCH {{hostname}}/monthly_balances/2
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "month": 12
}

### MONTHLY BALANCES DESTROY
DELETE {{hostname}}/monthly_balances/1
Authorization: Bearer {{jwt}}

### MONTHLY BALANCES NET CASH
GET {{hostname}}/net_cash
Authorization: Bearer {{jwt}}

### ------------------------------------------------------------------ ###

### CREATE USER
POST {{hostname}}/users
Content-Type: application/json

{
  "first_name": "Ryan",
  "last_name": "Ball",
  "email": "ball.ryan.rb@gmail.com",
  "password": "Acceptance1!",
  "password_confirmation": "Acceptance1!"
}

### LOGIN
POST {{hostname}}/sessions
Content-Type: application/json

{
  "email": "ball.ryan.rb@gmail.com",
  "password": "Acceptance1!"
}