# POST http://localhost:3000/users
# Content-Type: application/json

# {
#   "first_name": "Sid",
#   "last_name": "Giraffe",
#   "email": "sid@gmail.com",
#   "password": "password",
#   "password_confirmation": "password"
# }

POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "sid@gmail.com",
  "password": "password"
}