POST http://localhost:3000/users
Content-Type: application/json

{
  "first_name": "Ryan",
  "last_name": "Ball",
  "email": "ball.ryan.rb@gmail.com",
  "password": "Acceptance1!",
  "password_confirmation": "Acceptance1!"
}

# POST http://localhost:3000/sessions
# Content-Type: application/json

# {
#   "email": "sid@gmail.com",
#   "password": "password"
# }