# RecurringExpense.create!([
#   {category: "Software Engineering Tools", name: "Coursera", description: "Coursera monthly subscription", estimate: 42.44 ,user_id: 1},
#   {category: "Software Engineering Tools", name: "Heroku", description: "Sendero Heroku monthly payment", estimate: 7.00 ,user_id: 1},
#   {category: "Subscriptions", name: "Hulu", description: "Hulu monthly subscription", estimate: 7.61 ,user_id: 1},
#   {category: "Subscriptions", name: "Microsoft 365", description: "Microsoft 365 monthly subscription", estimate: 7.33 ,user_id: 1},
#   {category: "Rent & Utilities", name: "Public Storage", description: "Public Storage", estimate: 122.00 ,user_id: 1},
#   {category: "Rent & Utilities", name: "Courtney", description: "Courtney rent & utilities", estimate: -875.00 ,user_id: 1},
#   {category: "Rent & Utilities", name: "Regatta", description: "Regatta rent & utilities", estimate: 1625.00 ,user_id: 1},
#   {category: "Rent & Utilities", name: "Visible", description: "Visible phone plan", estimate: 59.25 ,user_id: 1},
#   {category: "Gas & Car", name: "Tiguan", description: "Tiguan monthly payment", estimate: 349.00 ,user_id: 1},
#   {category: "Gas & Car", name: "Progressive", description: "Progressive car insurance", estimate: 142.00 ,user_id: 1},
#   {category: "Subscriptions", name: "Spotify", description: "Spotify monthly subscription", estimate: 17.40 ,user_id: 1},
#   {category: "Subscriptions", name: "Disney PLUS", description: "Disney PLUS monthly subscription", estimate: 8.73 ,user_id: 1},
#   {category: "Rent & Utilities", name: "Google Webpass", description: "Google Webpass monthly internet", estimate: 70.00 ,user_id: 1},
#   {category: "Health Insurance", name: "Bright", description: "Bright health insurance", estimate: 181.65 ,user_id: 1},
#   {category: "Climbing & Fitness", name: "Movement", description: "Movement monthly membership", estimate: 85.00 ,user_id: 1},
#   {category: "Rent & Utilities", name: "State Farm", description: "State Farm renters insurance", estimate: 8.33 ,user_id: 1},
#   {category: "Subscriptions", name: "Netflix", description: "Netflix monthly subscription", estimate: 18.86 ,user_id: 1},
#   {category: "Rent & Utilities", name: "Shift", description: "Shift office rent", estimate: 699.00 ,user_id: 1}
#   ])