# RecurringExpense.create!([
#   {category: "Software Engineering Tools", description: "Coursera monthly subscription", estimate: 42.44 ,user_id: 1},
#   {category: "Software Engineering Tools", description: "Sendero Heroku monthly payment", estimate: 7.00 ,user_id: 1},
#   {category: "Subscriptions", description: "Hulu monthly subscription", estimate: 7.61 ,user_id: 1},
#   {category: "Subscriptions", description: "Microsoft 365 monthly subscription", estimate: 7.33 ,user_id: 1},
#   {category: "Rent & Utilities", description: "Public Storage", estimate: 122.00 ,user_id: 1},
#   {category: "Rent & Utilities", description: "Courtney rent & utilities", estimate: -875.00 ,user_id: 1},
#   {category: "Rent & Utilities", description: "Regatta rent & utilities", estimate: 1625.00 ,user_id: 1},
#   {category: "Rent & Utilities", description: "Visible phone plan", estimate: 59.25 ,user_id: 1},
#   {category: "Gas & Car", description: "Tiguan monthly payment", estimate: 349.00 ,user_id: 1},
#   {category: "Gas & Car", description: "Progressive car insurance", estimate: 142.00 ,user_id: 1},
#   {category: "Subscriptions", description: "Spotify monthly subscription", estimate: 17.40 ,user_id: 1},
#   {category: "Subscriptions", description: "Disney PLUS monthly subscription", estimate: 8.73 ,user_id: 1},
#   {category: "Rent & Utilities", description: "Google Webpass monthly internet", estimate: 70.00 ,user_id: 1},
#   {category: "Health Insurance", description: "Bright health insurance", estimate: 181.65 ,user_id: 1},
#   {category: "Climbing & Fitness", description: "Movement monthly membership", estimate: 85.00 ,user_id: 1},
#   {category: "Rent & Utilities", description: "State Farm renters insurance", estimate: 8.33 ,user_id: 1},
#   {category: "Subscriptions", description: "Netflix monthly subscription", estimate: 18.86 ,user_id: 1},
#   {category: "Rent & Utilities", description: "Shift office rent", estimate: 699.00 ,user_id: 1}
#   ])